name: Verify

on:
  pull_request:

jobs:
  pr-title-validation:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: rudderlabs/github-action-check-pr-title@v1.0.7

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Lint Checks
        run: |
          npm run lint
      
      - run: git diff --exit-code
      
      - name: Error message
        if: ${{ failure() }}
        run: echo 'Eslint check is failing Ensure you have run `npm run lint || npx eslint --fix . || npx eslint --fix <FILE_PATH>` and committed the files locally.'